# Generated by Django 4.2.7 on 2023-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
