# Generated by Django 4.2.7 on 2023-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0003_jobs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='ads',
            field=models.ImageField(default='media/job/default-ads.png', upload_to='media/job/'),
        ),
    ]
