# Generated by Django 4.2.7 on 2023-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0004_alter_jobs_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='ads',
            field=models.ImageField(default='media/job/default-ads.jpg', upload_to='media/job/'),
        ),
    ]
