# Generated by Django 4.2.7 on 2023-12-09 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0005_alter_jobs_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_title', models.CharField(blank=True, max_length=256)),
                ('email_description', models.TextField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
