# Generated by Django 4.2.7 on 2023-12-11 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0006_emailcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(blank=True, max_length=256)),
                ('user_email', models.CharField(blank=True, max_length=256)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_contact_no', models.CharField(blank=True, max_length=256)),
                ('user_degree', models.CharField(blank=True, max_length=256)),
                ('user_portfolio', models.CharField(blank=True, max_length=256)),
                ('user_tag_line', models.CharField(blank=True, max_length=256)),
                ('user_experience', models.CharField(blank=True, max_length=256)),
                ('user_image', models.ImageField(default='media/profile/default-ads.jpg', upload_to='media/profile/')),
                ('user_facebook', models.CharField(blank=True, max_length=256)),
                ('user_linkedin', models.CharField(blank=True, max_length=256)),
                ('user_skype', models.CharField(blank=True, max_length=256)),
                ('user_twitter', models.CharField(blank=True, max_length=256)),
                ('user_instagram', models.CharField(blank=True, max_length=256)),
                ('user_address', models.CharField(blank=True, max_length=256)),
                ('email_description', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
