# Generated by Django 4.2.7 on 2023-12-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0008_alter_resumepersonalinfo_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(blank=True, max_length=256)),
                ('skill_value', models.CharField(blank=True, max_length=256)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill_info', to='classify_resume.resumepersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('job_title', models.CharField(blank=True, max_length=256)),
                ('start_experience', models.DateField(blank=True, null=True)),
                ('end_experience', models.DateField(blank=True, null=True)),
                ('official_description', models.TextField(blank=True, max_length=1000)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_professional_info', to='classify_resume.resumepersonalinfo')),
            ],
        ),
    ]
