# Generated by Django 4.2.7 on 2023-12-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0009_skillinfo_professionalexperienceinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumepersonalinfo',
            old_name='email_description',
            new_name='about_description',
        ),
    ]
