# Generated by Django 4.2.7 on 2023-12-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0010_rename_email_description_resumepersonalinfo_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_salary', models.IntegerField(blank=True, default=0)),
                ('expected_salary', models.IntegerField(blank=True, default=0)),
                ('apply_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apply_job', to='classify_resume.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applied', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
