# Generated by Django 4.2.7 on 2023-12-20 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0011_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='apply_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 21, 1, 25, 13, 250093), null=True),
        ),
    ]
