# Generated by Django 4.2.7 on 2023-12-20 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0012_appliedjob_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='apply_status',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='apply_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 21, 1, 28, 14, 276600), null=True),
        ),
    ]
