# Generated by Django 4.2.7 on 2023-12-30 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0013_appliedjob_apply_status_alter_appliedjob_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='apply_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 30, 20, 8, 20, 305320), null=True),
        ),
        migrations.CreateModel(
            name='CertificateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_title', models.CharField(blank=True, max_length=500)),
                ('cert_image', models.ImageField(default='media/certificate/default-certificate.jpg', upload_to='media/certificate/')),
                ('cert_description', models.TextField(blank=True, max_length=1000)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cert_info', to='classify_resume.resumepersonalinfo')),
            ],
        ),
    ]
