# Generated by Django 4.2.7 on 2023-12-30 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_resume', '0014_alter_appliedjob_apply_date_certificateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='total_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='apply_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 30, 23, 41, 34, 825888), null=True),
        ),
    ]
